<a href="https://colab.research.google.com/github/Josh1313/hackathon/blob/main/hackaton2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
# habitat ciudad turistica
df =pd.read_csv("/content/drive/MyDrive/Clase 3 - Web scraping v2/hut_comunicacio_opendata.csv")

In [43]:
# pip install unidecode

In [44]:
# import pandas as pd
# from unidecode import unidecode

# # Función para quitar tildes, caracteres especiales y comas
# def remove_accents_special_chars_and_commas(text):
#     text = unidecode(text)
#     text = text.replace('-', '').replace(',', '')
#     return text

# # Aplicar la función a todas las celdas del DataFrame
# df = df.applymap(lambda x: remove_accents_special_chars_and_commas(x) if isinstance(x, str) else x)

# Seis codigos basicos para ver la informacio y visualizar si hay nulos , duplicados ,anomalias y datos que no aportan para borra

In [4]:
df.shape

(9734, 21)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9734 entries, 0 to 9733
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   N_EXPEDIENT                  9733 non-null   object
 1   CODI_DISTRICTE               9733 non-null   float64
 2   DISTRICTE                    9733 non-null   object
 3   CODI_BARRI                   9728 non-null   float64
 4   BARRI                        9722 non-null   object
 5   TIPUS_CARRER                 9733 non-null   object
 6   CARRER                       9733 non-null   object
 7   TIPUS_NUM                    9733 non-null   float64
 8   NUM1                         9733 non-null   float64
 9   LLETRA1                      117 non-null    object
 10  NUM2                         813 non-null    float64
 11  LLETRA2                      3 non-null      object
 12  BLOC                         10 non-null     object
 13  PORTAL                       40 non-null     object
 14  ESCALA                       703 non-null    object
 15  PIS                          9702 non-null   object
 16  PORTA                        8830 non-null   object
 17  NUMERO_REGISTRE_GENERALITAT  9699 non-null   object
 18  NUMERO_PLACES                9682 non-null   float64
 19  LONGITUD_X                   9733 non-null   float64
 20  LATITUD_Y                    9733 non-null   float64
dtypes: float64(8), object(13)
memory usage: 1.6+ MB

In [6]:
df.describe()

,CODI_DISTRICTE,CODI_BARRI,TIPUS_NUM,NUM1,NUM2,NUMERO_PLACES,LONGITUD_X,LATITUD_Y
count,9733.000000,9728.000000,9733.000000,9733.000000,813.000000,9682.000000,9733.000000,9733.000000
mean,3.887599,20.275493,1.468406,134.137881,122.193112,5.967465,2.164041,41.391311
std,2.791807,19.985339,0.499026,150.875594,134.530174,3.514939,0.018064,0.012716
min,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,2.092180,41.350747
25%,2.000000,7.000000,1.000000,24.000000,23.000000,4.000000,2.153364,41.380769
50%,2.000000,10.000000,1.000000,73.000000,71.000000,5.000000,2.163578,41.391700
75%,6.000000,31.000000,2.000000,201.000000,157.000000,7.000000,2.174010,41.400706
max,10.000000,73.000000,2.000000,1021.000000,1023.000000,79.000000,2.217988,41.450940

In [7]:
df.head(5)

,N_EXPEDIENT,CODI_DISTRICTE,DISTRICTE,CODI_BARRI,BARRI,TIPUS_CARRER,CARRER,TIPUS_NUM,NUM1,LLETRA1,...,LLETRA2,BLOC,PORTAL,ESCALA,PIS,PORTA,NUMERO_REGISTRE_GENERALITAT,NUMERO_PLACES,LONGITUD_X,LATITUD_Y
0,01-2013-0753,1.0,CIUTAT VELLA,1.0,el Raval,Carrer,HOSPITAL,1.0,25.0,NaN,...,NaN,NaN,NaN,NaN,1,2,HUTB-000715,9.0,2.171125,41.379035
1,02-2014-0566,2.0,L'EIXAMPLE,6.0,la Sagrada Família,Avinguda,GAUDI,1.0,51.0,NaN,...,NaN,NaN,NaN,NaN,EN,1,HUTB-010412,7.0,2.173113,41.406595
2,02-2014-0207,2.0,L'EIXAMPLE,7.0,la Dreta de l'Eixample,Plaça,TETUAN,1.0,33.0,NaN,...,NaN,NaN,NaN,NaN,SA,2,HUTB-008754,4.0,2.174958,41.393788
3,01-2014-0073,1.0,CIUTAT VELLA,1.0,el Raval,Carrer,JUNTA DE COMERÇ,1.0,23.0,NaN,...,NaN,NaN,NaN,NaN,2,1A,HUTB-013228,4.0,2.170788,41.377598
4,02-2014-1125,2.0,L'EIXAMPLE,7.0,la Dreta de l'Eixample,Gran Via,CORTS CATALANES,2.0,682.0,NaN,...,NaN,NaN,NaN,NaN,2,1,HUTB-011029,8.0,2.171954,41.390836

In [8]:
df.isnull().sum()

N_EXPEDIENT                       1
CODI_DISTRICTE                    1
DISTRICTE                         1
CODI_BARRI                        6
BARRI                            12
TIPUS_CARRER                      1
CARRER                            1
TIPUS_NUM                         1
NUM1                              1
LLETRA1                        9617
NUM2                           8921
LLETRA2                        9731
BLOC                           9724
PORTAL                         9694
ESCALA                         9031
PIS                              32
PORTA                           904
NUMERO_REGISTRE_GENERALITAT      35
NUMERO_PLACES                    52
LONGITUD_X                        1
LATITUD_Y                         1
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
#Borramos filas nulas
df.dropna(inplace=True)

In [11]:
df.head()

Empty DataFrame
Columns: [N_EXPEDIENT, CODI_DISTRICTE, DISTRICTE, CODI_BARRI, BARRI, TIPUS_CARRER, CARRER, TIPUS_NUM, NUM1, LLETRA1, NUM2, LLETRA2, BLOC, PORTAL, ESCALA, PIS, PORTA, NUMERO_REGISTRE_GENERALITAT, NUMERO_PLACES, LONGITUD_X, LATITUD_Y]
Index: []

[0 rows x 21 columns]

In [37]:
df.isnull().sum()

N_EXPEDIENT                    0.0
CODI_DISTRICTE                 0.0
DISTRICTE                      0.0
CODI_BARRI                     0.0
BARRI                          0.0
TIPUS_CARRER                   0.0
CARRER                         0.0
TIPUS_NUM                      0.0
NUM1                           0.0
LLETRA1                        0.0
NUM2                           0.0
LLETRA2                        0.0
BLOC                           0.0
PORTAL                         0.0
ESCALA                         0.0
PIS                            0.0
PORTA                          0.0
NUMERO_REGISTRE_GENERALITAT    0.0
NUMERO_PLACES                  0.0
LONGITUD_X                     0.0
LATITUD_Y                      0.0
dtype: float64

In [38]:
df

Empty DataFrame
Columns: [N_EXPEDIENT, CODI_DISTRICTE, DISTRICTE, CODI_BARRI, BARRI, TIPUS_CARRER, CARRER, TIPUS_NUM, NUM1, LLETRA1, NUM2, LLETRA2, BLOC, PORTAL, ESCALA, PIS, PORTA, NUMERO_REGISTRE_GENERALITAT, NUMERO_PLACES, LONGITUD_X, LATITUD_Y]
Index: []

[0 rows x 21 columns]

In [ ]:

columnas_a_borrar = ['NUM1', 'LLETRA1', 'LLETRA2', 'BLOC', 'PORTAL', 'NUM2', 'ESCALA']

df = df.drop(columns=columnas_a_borrar)

In [ ]:
df.head(5)

Empty DataFrame
Columns: [N_EXPEDIENT, CODI_DISTRICTE, DISTRICTE, CODI_BARRI, BARRI, TIPUS_CARRER, CARRER, TIPUS_NUM, PIS, PORTA, NUMERO_REGISTRE_GENERALITAT, NUMERO_PLACES, LONGITUD_X, LATITUD_Y]
Index: []

In [ ]:
df.rename(columns={'DISTRICTE': 'ZONA'}, inplace=True)

In [ ]:
df.head()

,N_EXPEDIENT,CODI_DISTRICTE,ZONA,CODI_BARRI,BARRI,TIPUS_CARRER,CARRER,TIPUS_NUM,PIS,PORTA,NUMERO_REGISTRE_GENERALITAT,NUMERO_PLACES,LONGITUD_X,LATITUD_Y
0,0120130753,1.000,CIUTAT VELLA,1.000,el Raval,Carrer,HOSPITAL,1.000,1,2,HUTB000715,9.000,2.171,41.379
1,0220140566,2.000,L'EIXAMPLE,6.000,la Sagrada Familia,Avinguda,GAUDI,1.000,EN,1,HUTB010412,7.000,2.173,41.407
2,0220140207,2.000,L'EIXAMPLE,7.000,la Dreta de l'Eixample,Placa,TETUAN,1.000,SA,2,HUTB008754,4.000,2.175,41.394
3,0120140073,1.000,CIUTAT VELLA,1.000,el Raval,Carrer,JUNTA DE COMERC,1.000,2,1A,HUTB013228,4.000,2.171,41.378
4,0220141125,2.000,L'EIXAMPLE,7.000,la Dreta de l'Eixample,Gran Via,CORTS CATALANES,2.000,2,1,HUTB011029,8.000,2.172,41.391

In [ ]:
df['TIPUS_CARRER'].value_counts()

Carrer        7643
Passeig        518
Avinguda       491
Gran Via       220
Rambla         214
Ronda          201
Passatge       174
Placa          112
Travessera     112
Via             30
Carretera        7
Riera            7
Baixada          2
Travessia        1
Costa            1
Name: TIPUS_CARRER, dtype: int64

In [ ]:
df['CARRER'].value_counts()

GRACIA                   307
VALENCIA                 298
CORTS CATALANES          219
ARAGO                    208
CONSELL DE CENT          202
                        ...
PLANETA                    1
MARE DE DEU DELS REIS      1
SEGURA                     1
RUBENS                     1
AVENIR                     1
Name: CARRER, Length: 903, dtype: int64

In [ ]:
cantidad_valores_unicos = df['BARRI'].nunique()
print("Número de valores únicos en la columna 'BARRI':", cantidad_valores_unicos)

Número de valores únicos en la columna 'BARRI': 64

In [ ]:
#  'BARRI' es la columna que  interesa para poder darle un rating a las barrios del 1 al 10 y esto se asigna por la intensidad o las veces que han visitado ese bario
intensidad_counts = df['BARRI'].value_counts()

# Imprimir los valores únicos junto con su frecuencia
print("Valores únicos en la columna 'BARRI' y su frecuencia:")
print(intensidad_counts)

Valores únicos en la columna 'INTENSIDAD' y su frecuencia:
la Dreta de l'Eixample             1644
la Vila de Gracia                   752
la Sagrada Familia                  749
l'Antiga Esquerra de l'Eixample     667
la Nova Esquerra de l'Eixample      558
                                   ...
les Roquetes                          2
el Bon Pastor                         1
la Guineueta                          1
la Vall d'Hebron                      1
Canyelles                             1
Name: BARRI, Length: 64, dtype: int64

In [ ]:

# # Suponiendo que ya has calculado intensidad_counts
# intensidad_counts = df['BARRI'].value_counts()

# # Calcular la media de la sumatoria de visitas por barrio
# mean_intensity = intensidad_counts.mean()

# # Crear una nueva columna con la media de la sumatoria de visitas por barrio
# df['MEDIA_INTENSIDAD'] = mean_intensity

# # Crear la columna de "rating" basada en la media
# df['RATING'] = pd.qcut(intensidad_counts, q=10, labels=False, precision=0)

# # Ajustar los valores de rating para que comiencen desde 1 en lugar de 0
# df['RATING'] = df['RATING'] + 1

In [ ]:
df.isnull().sum()

N_EXPEDIENT                       1
CODI_DISTRICTE                    1
ZONA                              1
CODI_BARRI                        6
BARRI                            12
TIPUS_CARRER                      1
CARRER                            1
TIPUS_NUM                         1
PIS                              32
PORTA                           904
NUMERO_REGISTRE_GENERALITAT      35
NUMERO_PLACES                    52
LONGITUD_X                        1
LATITUD_Y                         1
MEDIA_INTENSIDAD                  0
RATING                         9734
dtype: int64

In [ ]:
import pandas as pd


#Crear un diccionario de mapeo asignando valores de 1 a 10 a las zonas
intensidad1_mapping = {
    'L\'EIXAMPLE': 10,
    'SANT MARTI': 9,
    'SANTS-MONTJUÏC': 8,
    'GRACIA': 7,
    'SARRIA-SANT GERVASI': 6,
    'CIUTAT VELLA': 5,
    'LES CORTS': 4,
    'HORTA-GUINARDÓ': 3,
    'SANT ANDREU': 2,
    'NOU BARRIS': 1
}

#Crear la nueva columna 'INTENSIDAD1' utilizando el mapeo
df['INTENSIDAD'] = df['ZONA'].map(intensidad1_mapping)

In [ ]:
columnas_a_borrar = ['PORTA','CARRER', 'TIPUS_CARRER', 'N_EXPEDIENT', 'CODI_DISTRICTE', 'CODI_BARRI', 'TIPUS_NUM', 'PIS', 'NUMERO_REGISTRE_GENERALITAT', 'NUMERO_PLACES', 'LONGITUD_X', 'LATITUD_Y']

# Crea un nuevo DataFrame sin las columnas especificadas
df = df.drop(columns=columnas_a_borrar)

In [ ]:
df.head(5)

Empty DataFrame
Columns: [ZONA, BARRI, INTENSIDAD]
Index: []

In [ ]:
df.head(15)

Empty DataFrame
Columns: [ZONA, BARRI, INTENSIDAD]
Index: []

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.drop_duplicates(inplace=True)

Empty DataFrame
Columns: [ZONA, BARRI, INTENSIDAD]
Index: []

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ZONA        0 non-null      object
 1   BARRI       0 non-null      object
 2   INTENSIDAD  0 non-null      int64
dtypes: int64(1), object(2)
memory usage: 0.0+ bytes

In [ ]:
df.rename(columns={'INTENSIDAD': 'RATING'}, inplace=True)

In [ ]:
df.head()

Empty DataFrame
Columns: [ZONA, BARRI, RATING]
Index: []

In [ ]:
import pandas as pd
from unidecode import unidecode

# Función para quitar tildes, caracteres especiales y comas
def remove_accents_special_chars_and_commas(text):
    text = unidecode(text)
    text = text.replace('-', '').replace(',', '')
    return text

# Aplicar la función a todas las celdas del DataFrame
df = df.applymap(lambda x: remove_accents_special_chars_and_commas(x) if isinstance(x, str) else x)

In [ ]:

df_agregado = df.groupby(['ZONA', 'BARRI']).agg({  # Agrega la coma que falta aquí
    'RATING': 'first'
}).reset_index()

In [ ]:
df_agregado.head()

Empty DataFrame
Columns: [ZONA, BARRI, RATING]
Index: []

In [ ]:
df_agregado.shape

(0, 3)

empiezo el nuevo

In [ ]:
codificaciones = ['UTF-16', 'latin-1', 'ISO-8859-1', 'cp1252']

for codificacion in codificaciones:
    try:
        df11 = pd.read_csv("/content/drive/MyDrive/Clase 3 - Web scraping v2/opendatabcn_pics-csv.csv", encoding=codificacion)
        print(f"Lectura exitosa con codificación: {codificacion}")
        break  # Sale del bucle si la lectura es exitosa
    except UnicodeDecodeError:
        print(f"Fallo en la lectura con codificación: {codificacion}")

# Si llegas a este punto y df11 no está definido, podría ser necesario ajustar la codificación o el archivo

Lectura exitosa con codificación: UTF-16

In [ ]:
df11.head()

,register_id,name,institution_id,institution_name,created,modified,addresses_roadtype_id,addresses_roadtype_name,addresses_road_id,addresses_road_name,...,values_attribute_id,values_category,values_attribute_name,values_value,values_outstanding,values_description,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,﻿92086012294,Casa Marsans - Alberg Mare de Déu de Montserra...,NaN,NaN,1988-02-15T00:00:00+01:00,2022-09-23T14:50:17.987863+02:00,NaN,NaN,230000,Pg Mare de Déu del Coll,...,100002.0,Informació d'interès,E-mail,reserves.xanascat@gencat.cat,True,NaN,428703.038291,4.585311e+06,41.416189,2.146866
1,﻿92086007892,Escola d'Aprenents SEAT,NaN,NaN,1985-05-31T00:00:00+02:00,2022-09-17T04:02:54.481066+02:00,NaN,NaN,369408,Pg Zona Franca,...,100002.0,Informació d'interès,E-mail,a8032427@xtec.cat,True,NaN,428306.184605,4.578458e+06,41.354433,2.142929
2,﻿92086009449,Mercat Concepció,NaN,NaN,1984-12-28T00:00:00+01:00,2023-06-15T11:05:32.197343+02:00,NaN,NaN,18505,Carrer d'Aragó,...,100005.0,Informació d'interès,Facebook,https://www.facebook.com/MercatConcepcio,False,NaN,430536.809960,4.583003e+06,41.395568,2.169072
3,﻿99400400974,El Campus Raval - UB,NaN,NaN,2015-11-10T09:21:37+01:00,2022-09-23T14:43:53.592959+02:00,NaN,NaN,216906,C Montalegre,...,100003.0,Informació d'interès,Web,https://www.ub.edu/portal/web/geografia-histor...,True,NaN,430342.994107,4.581730e+06,41.384077,2.166900
4,﻿92086009452,Mercat Sant Antoni,NaN,NaN,1990-06-25T00:00:00+02:00,2023-06-16T10:52:47.863399+02:00,NaN,NaN,349706,Carrer del Comte d'Urgell,...,100005.0,Informació d'interès,Facebook,https://www.facebook.com/mercatstantoni/,False,NaN,429906.977449,4.581233e+06,41.379568,2.161743

In [ ]:
df11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   register_id                    882 non-null    object
 1   name                           882 non-null    object
 2   institution_id                 25 non-null     float64
 3   institution_name               25 non-null     object
 4   created                        882 non-null    object
 5   modified                       882 non-null    object
 6   addresses_roadtype_id          0 non-null      float64
 7   addresses_roadtype_name        0 non-null      float64
 8   addresses_road_id              882 non-null    int64
 9   addresses_road_name            882 non-null    object
 10  addresses_start_street_number  860 non-null    float64
 11  addresses_end_street_number    60 non-null     float64
 12  addresses_neighborhood_id      882 non-null    int64
 13  addresses_neighborhood_name    882 non-null    object
 14  addresses_district_id          882 non-null    int64
 15  addresses_district_name        882 non-null    object
 16  addresses_zip_code             882 non-null    int64
 17  addresses_town                 882 non-null    object
 18  addresses_main_address         882 non-null    bool
 19  addresses_type                 0 non-null      float64
 20  values_id                      601 non-null    float64
 21  values_attribute_id            601 non-null    float64
 22  values_category                601 non-null    object
 23  values_attribute_name          601 non-null    object
 24  values_value                   601 non-null    object
 25  values_outstanding             601 non-null    object
 26  values_description             1 non-null      object
 27  geo_epgs_25831_x               882 non-null    float64
 28  geo_epgs_25831_y               882 non-null    float64
 29  geo_epgs_4326_x                882 non-null    float64
 30  geo_epgs_4326_y                882 non-null    float64
dtypes: bool(1), float64(12), int64(4), object(14)
memory usage: 207.7+ KB

In [ ]:
columnas_a_borrar = [
    'register_id', 'institution_id', 'institution_name', 'created', 'modified',
    'addresses_roadtype_id', 'addresses_roadtype_name',
    'addresses_end_street_number', 'addresses_neighborhood_id',
    'addresses_district_id', 'addresses_district_name', 'addresses_zip_code',
    'addresses_town', 'addresses_main_address', 'addresses_type', 'values_id',
    'values_attribute_id', 'values_category', 'values_attribute_name', 'values_value',
    'values_outstanding', 'values_description', 'addresses_road_id'
]

# Crea un nuevo DataFrame sin las columnas especificadas
df11 = df11.drop(columns=columnas_a_borrar)

In [ ]:
df11.head()

,name,addresses_road_name,addresses_start_street_number,addresses_neighborhood_name,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,Casa Marsans - Alberg Mare de Déu de Montserra...,Pg Mare de Déu del Coll,41.0,Vallcarca i els Penitents,428703.038291,4.585311e+06,41.416189,2.146866
1,Escola d'Aprenents SEAT,Pg Zona Franca,53.0,la Marina del Prat Vermell,428306.184605,4.578458e+06,41.354433,2.142929
2,Mercat Concepció,Carrer d'Aragó,311.0,la Dreta de l'Eixample,430536.809960,4.583003e+06,41.395568,2.169072
3,El Campus Raval - UB,C Montalegre,6.0,el Raval,430342.994107,4.581730e+06,41.384077,2.166900
4,Mercat Sant Antoni,Carrer del Comte d'Urgell,1.0,Sant Antoni,429906.977449,4.581233e+06,41.379568,2.161743

In [ ]:
df11['addresses_neighborhood_name'].value_counts()

la Vila de Gràcia         87
Sant Andreu               63
la Dreta de l'Eixample    56
el Poble-sec              53
el Raval                  39
                          ..
Vallbona                   1
Verdun                     1
Torre Baró                 1
Baró de Viver              1
la Verneda i la Pau        1
Name: addresses_neighborhood_name, Length: 68, dtype: int64

In [ ]:
df11.rename(columns={'addresses_neighborhood_name': 'BARRI', 'addresses_road_name': 'CARRER', 'name':'NAME'}, inplace=True)

In [ ]:
df11.head(5)

,NAME,CARRER,addresses_start_street_number,BARRI,geo_epgs_25831_x,geo_epgs_25831_y,geo_epgs_4326_x,geo_epgs_4326_y
0,Casa Marsans - Alberg Mare de Déu de Montserra...,Pg Mare de Déu del Coll,41.0,Vallcarca i els Penitents,428703.038291,4.585311e+06,41.416189,2.146866
1,Escola d'Aprenents SEAT,Pg Zona Franca,53.0,la Marina del Prat Vermell,428306.184605,4.578458e+06,41.354433,2.142929
2,Mercat Concepció,Carrer d'Aragó,311.0,la Dreta de l'Eixample,430536.809960,4.583003e+06,41.395568,2.169072
3,El Campus Raval - UB,C Montalegre,6.0,el Raval,430342.994107,4.581730e+06,41.384077,2.166900
4,Mercat Sant Antoni,Carrer del Comte d'Urgell,1.0,Sant Antoni,429906.977449,4.581233e+06,41.379568,2.161743

In [ ]:
df_merged = pd.merge(df, df11, on='BARRI', how='inner')

In [ ]:
df_merged.head()

Empty DataFrame
Columns: [ZONA, RATING, NAME, CARRER, addresses_start_street_number, BARRI, geo_epgs_25831_x, geo_epgs_25831_y, geo_epgs_4326_x, geo_epgs_4326_y]
Index: []

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ZONA                           0 non-null      object
 1   RATING                         0 non-null      int64
 2   NAME                           0 non-null      object
 3   CARRER                         0 non-null      object
 4   addresses_start_street_number  0 non-null      float64
 5   BARRI                          0 non-null      object
 6   geo_epgs_25831_x               0 non-null      float64
 7   geo_epgs_25831_y               0 non-null      float64
 8   geo_epgs_4326_x                0 non-null      float64
 9   geo_epgs_4326_y                0 non-null      float64
dtypes: float64(5), int64(1), object(4)
memory usage: 0.0+ bytes

In [ ]:
df_merged.isnull().sum()

ZONA                             0.0
RATING                           0.0
NAME                             0.0
CARRER                           0.0
addresses_start_street_number    0.0
BARRI                            0.0
geo_epgs_25831_x                 0.0
geo_epgs_25831_y                 0.0
geo_epgs_4326_x                  0.0
geo_epgs_4326_y                  0.0
dtype: float64

In [ ]:
df_merged = df_merged.dropna()

In [ ]:
df_merged.isnull().sum()

ZONA                             0.0
RATING                           0.0
NAME                             0.0
CARRER                           0.0
addresses_start_street_number    0.0
BARRI                            0.0
geo_epgs_25831_x                 0.0
geo_epgs_25831_y                 0.0
geo_epgs_4326_x                  0.0
geo_epgs_4326_y                  0.0
dtype: float64

In [ ]:
df.duplicated().sum()

0

In [ ]:
import pandas as pd
from unidecode import unidecode

# Supongamos que 'df_media' es tu DataFrame

# Función para quitar tildes, caracteres especiales y comas
def remove_accents_special_chars_and_commas(text):
    text = unidecode(text)
    text = text.replace('-', "").replace(',', '').replace("'", '')
    return text

# Aplicar la función a todas las celdas del DataFrame
df_merged = df_merged.applymap(lambda x: remove_accents_special_chars_and_commas(x) if isinstance(x, str) else x)

In [ ]:
df_merged['BARRI'] = df_merged['BARRI'].str.upper()

In [ ]:
df_merged.replace(' ', '_', regex=True, inplace=True)

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ZONA                           0 non-null      object
 1   RATING                         0 non-null      int64
 2   NAME                           0 non-null      object
 3   CARRER                         0 non-null      object
 4   addresses_start_street_number  0 non-null      float64
 5   BARRI                          0 non-null      object
 6   geo_epgs_25831_x               0 non-null      float64
 7   geo_epgs_25831_y               0 non-null      float64
 8   geo_epgs_4326_x                0 non-null      float64
 9   geo_epgs_4326_y                0 non-null      float64
dtypes: float64(5), int64(1), object(4)
memory usage: 0.0+ bytes

In [ ]:
df_merged.tail(25)

Empty DataFrame
Columns: [ZONA, RATING, NAME, CARRER, addresses_start_street_number, BARRI, geo_epgs_25831_x, geo_epgs_25831_y, geo_epgs_4326_x, geo_epgs_4326_y]
Index: []

In [ ]:
df_merged['CATEGORIAS'] = 'ATRACCIONES'

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ZONA                           0 non-null      object
 1   RATING                         0 non-null      int64
 2   NAME                           0 non-null      object
 3   CARRER                         0 non-null      object
 4   addresses_start_street_number  0 non-null      float64
 5   BARRI                          0 non-null      object
 6   geo_epgs_25831_x               0 non-null      float64
 7   geo_epgs_25831_y               0 non-null      float64
 8   geo_epgs_4326_x                0 non-null      float64
 9   geo_epgs_4326_y                0 non-null      float64
 10  CATEGORIAS                     0 non-null      object
dtypes: float64(5), int64(1), object(5)
memory usage: 0.0+ bytes

In [ ]:
df_merged['addresses_start_street_number'] = df_merged['addresses_start_street_number'].astype(int)

In [ ]:

df_merged['ADDRESS'] = df_merged['CARRER'].astype(str) + ',' + df_merged['addresses_start_street_number'].astype(str)

In [ ]:
df_merged.head(5)

Empty DataFrame
Columns: [ZONA, RATING, NAME, CARRER, addresses_start_street_number, BARRI, geo_epgs_25831_x, geo_epgs_25831_y, geo_epgs_4326_x, geo_epgs_4326_y, CATEGORIAS, ADDRESS]
Index: []

In [ ]:
columnas_borrar=['addresses_start_street_number', 'geo_epgs_4326_x','geo_epgs_4326_y','CARRER']

In [ ]:
df_merged = df_merged.drop(['addresses_start_street_number', 'geo_epgs_4326_x', 'geo_epgs_4326_y'], axis=1)

In [ ]:
df_merged.head(5)

Empty DataFrame
Columns: [ZONA, RATING, NAME, CARRER, BARRI, geo_epgs_25831_x, geo_epgs_25831_y, CATEGORIAS, ADDRESS]
Index: []

In [ ]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

del df_merged['ZONA']
del df_merged['CARRER']

In [ ]:
df_merged.rename(columns={'geo_epgs_25831_x': 'LONGITUD', 'geo_epgs_25831_y': 'LATITUD', 'BARRI' :'ZONA'}, inplace=True)

In [ ]:
df_merged.columns = df_merged.columns.str.lower()

In [ ]:
df_merged.head(5)

Empty DataFrame
Columns: [rating, name, zona, longitud, latitud, categorias, address]
Index: []

In [ ]:
df_merged.to_json('Rating_Punto_Interes.json', orient='records', lines=True)

In [ ]:
df_merged.to_csv('punto de interes.csv', index=False)